spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.1.112/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.5.65/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.1.120/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties.hibernate.enable_lazy_load_no_trans : true


#server:
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: D:\sourcecode\wechatSell\log
#  file: D:\sourcecode\wechatSell\log\sell.log
#  level:
#    com.imocc: debug
